
project_id = "yulhsufpnjkiozkrgyoq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://yulhsufpnjkiozkrgyoq.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54323

[functions.chat-openai]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = true

[functions.match-documents-hierarchical]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.cleanup-data]
verify_jwt = true

[functions.chat-openai-stream]
verify_jwt = true

[functions.chat-direct-openai]
verify_jwt = true

[functions.chat-completions-stream]
verify_jwt = true

[functions.search-cds-vectorial]
verify_jwt = true

# Training functions
[functions.generate-animated-training]
verify_jwt = true

[functions.generate-training-question]
verify_jwt = true

[functions.prepa-cds-chat]
verify_jwt = true

[functions.evaluate-user-answer]
verify_jwt = true

[functions.generate-case-study]
verify_jwt = true

# Job board functions
[functions.jobs-create]
verify_jwt = true

[functions.jobs-list]
verify_jwt = false

[functions.jobs-search-ai]
verify_jwt = true

[functions.jobs-delete]
verify_jwt = true

[functions.jobs-communes]
verify_jwt = false

[functions.jobs-cleanup]
verify_jwt = true

[db]
enabled = true
port = 54322
